# Generated by Django 5.2.2 on 2025-06-24 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_label', models.CharField(max_length=1)),
                ('seat_number', models.IntegerField()),
                ('seat_type', models.CharField(choices=[('silver', 'silver'), ('gold', 'gold'), ('platinum', 'platinum')], max_length=100)),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Theatres.theater')),
            ],
        ),
    ]
