# Generated by Django 5.2.2 on 2025-06-24 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0003_movie_slug_alter_cast_name_alter_cast_role_and_more'),
        ('Theatres', '0002_rename_theater_theatre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='theater',
            new_name='theatre',
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_time', models.DateTimeField()),
                ('silver_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gold_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('recliner_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies.movie')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Theatres.theatre')),
            ],
        ),
    ]
