# Generated by Django 5.2.2 on 2025-06-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='cast',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cast',
            name='role',
            field=models.CharField(blank=True, choices=[('Hero', 'Hero'), ('Heroine', 'Heroine'), ('Supporting Actor', 'Supporting Actor'), ('Villain', 'Villain')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Animation', 'Animation'), ('Comedy', 'Comedy'), ('Crime', 'Crime'), ('Documentary', 'Documentary'), ('Drama', 'Drama'), ('Family', 'Family'), ('Fantasy', 'Fantasy'), ('History', 'History'), ('Horror', 'Horror'), ('Romance', 'Romance')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Hindi', 'Hindi'), ('kannada', 'Kannada'), ('Telugu', 'Telugu'), ('Tamil', 'Tamil'), ('Malayalam', 'Malayalam'), ('Bengali', 'Bengali'), ('Punjabi', 'Punjabi')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(blank=True, choices=[('Upcoming', 'Upcoming'), ('Released', 'Released')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=225),
        ),
    ]
